# Generated by Django 5.0.7 on 2024-08-02 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorias_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('clientes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.clientes')),
                ('Productos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField()),
                ('contenido', models.TextField()),
                ('fecha', models.DateField()),
                ('Clientes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.clientes')),
                ('Productos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.productos')),
            ],
        ),
    ]
